---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 02-vault
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  source:
    repoURL: https://github.com/eformat/secure-agent-workspace-gitops
    targetRevision: main
    path: applications/vault/base
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - Validate=true
