---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-cnv
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: openshift-cnv
    includeCRDs: true
    releaseName: openshift-cnv
