apiVersion: saw.redhat.com/v1alpha1
kind: Providers
metadata: {}
spec:
  providers:
    - name: openai
      type: openai
      nemoclawProvider: codex
      model: glm-53-flash
      credentialSecret: inference
      credentialSecretKey: api_key
